% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Dec-2021 11:54:32
%  MATLAB version: 9.8.0.1538580 (R2020a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('test.mat');

H = saveVarsMat.H; % <1x1 tf> unsupported class

clear saveVarsMat;
